const fs = require('fs');
const pi = require('react-icons/pi');
const availableIcons = Object.keys(pi);

const map = {
  Activity: 'PiActivityFill',
  AlertCircle: 'PiInfoFill',
  AlertTriangle: 'PiWarningFill',
  ArrowDown: 'PiArrowDownBold',
  ArrowDownToLine: 'PiDownloadSimpleBold',
  ArrowLeft: 'PiCaretLeftBold',
  AudioLines: 'PiWaveformBold',
  BadgeCheck: 'PiSealCheckFill',
  Bell: 'PiBellFill',
  BellOff: 'PiBellSlashFill',
  BellRing: 'PiBellRingingFill',
  BookOpen: 'PiBookOpenFill',
  Building2: 'PiBuildingsFill',
  Cake: 'PiCakeFill',
  CalendarCheck: 'PiCalendarCheckFill',
  CalendarClock: 'PiCalendarFill',
  Camera: 'PiCameraFill',
  CameraOff: 'PiCameraSlashFill',
  Car: 'PiCarFill',
  Check: 'PiCheckBold',
  CheckCircle: 'PiCheckCircleFill',
  CheckCircle2: 'PiCheckCircleFill',
  ChevronDown: 'PiCaretDownBold',
  ChevronLeft: 'PiCaretLeftBold',
  ChevronRight: 'PiCaretRightBold',
  ChevronUp: 'PiCaretUpBold',
  CircleDollarSign: 'PiCurrencyDollarSimpleFill',
  CircleDot: 'PiCircleFill',
  Clock: 'PiClockFill',
  Coins: 'PiCoinsFill',
  Copy: 'PiCopyFill',
  CreditCard: 'PiCreditCardFill',
  Crown: 'PiCrownFill',
  Delete: 'PiBackspaceFill',
  Dices: 'PiDiceFiveFill',
  FileText: 'PiFileTextFill',
  Flag: 'PiFlagFill',
  Flame: 'PiFireFill',
  FlipHorizontal: 'PiArrowsLeftRightBold',
  Gamepad2: 'PiGameControllerFill',
  Gem: 'PiDiamondFill',
  Gift: 'PiGiftFill',
  Globe: 'PiGlobeHemisphereWestFill',
  Headphones: 'PiHeadphonesFill',
  Heart: 'PiHeartFill',
  HelpCircle: 'PiQuestionFill',
  History: 'PiClockCounterClockwiseFill',
  Image: 'PiImageFill',
  Info: 'PiInfoFill',
  KeyRound: 'PiKeyFill',
  LayoutGrid: 'PiSquaresFourFill',
  Lightbulb: 'PiLightbulbFill',
  LineChart: 'PiChartLineUpFill',
  Link2: 'PiLinkBold',
  Loader2: 'PiSpinnerBold',
  Lock: 'PiLockFill',
  LogOut: 'PiSignOutBold',
  Mail: 'PiEnvelopeSimpleFill',
  MapPin: 'PiMapPinFill',
  Medal: 'PiMedalFill',
  Megaphone: 'PiMegaphoneFill',
  MessageCircle: 'PiChatCircleFill',
  MessageSquare: 'PiChatTeardropFill',
  Mic: 'PiMicrophoneFill',
  MicOff: 'PiMicrophoneSlashFill',
  Moon: 'PiMoonFill',
  MoreHorizontal: 'PiDotsThreeBold',
  MoreVertical: 'PiDotsThreeVerticalBold',
  Music: 'PiMusicNoteFill',
  Music4: 'PiMusicNotesFill',
  Orbit: 'PiPlanetFill',
  Package: 'PiPackageFill',
  Pause: 'PiPauseFill',
  Phone: 'PiPhoneFill',
  PhoneCall: 'PiPhoneCallFill',
  PhoneOff: 'PiPhoneSlashFill',
  Plane: 'PiAirplaneFill',
  Play: 'PiPlayFill',
  Plus: 'PiPlusBold',
  Radio: 'PiRadioFill',
  Repeat: 'PiArrowsClockwiseBold',
  RotateCcw: 'PiArrowCounterClockwiseBold',
  Save: 'PiFloppyDiskFill',
  Search: 'PiMagnifyingGlassBold',
  Send: 'PiPaperPlaneRightFill',
  Settings: 'PiGearFill',
  Settings2: 'PiSlidersFill',
  Share2: 'PiShareNetworkFill',
  ShieldAlert: 'PiShieldWarningFill',
  ShieldCheck: 'PiShieldCheckFill',
  Shirt: 'PiTShirtFill',
  ShoppingBag: 'PiToteFill',
  SlidersHorizontal: 'PiSlidersHorizontalFill',
  Smile: 'PiSmileyFill',
  Sparkles: 'PiSparkleFill',
  Star: 'PiStarFill',
  Sticker: 'PiStickerFill',
  Store: 'PiStorefrontFill',
  Sun: 'PiSunFill',
  Swords: 'PiSwordFill',
  Tag: 'PiTagFill',
  Trash2: 'PiTrashFill',
  Trophy: 'PiTrophyFill',
  Tv: 'PiTelevisionFill',
  Undo2: 'PiArrowUUpLeftBold',
  Unlink: 'PiLinkBreakBold',
  Upload: 'PiUploadSimpleBold',
  User: 'PiUserFill',
  UserCog: 'PiUserGearFill',
  UserPlus: 'PiUserPlusFill',
  UserRound: 'PiUserCircleFill',
  UserSquare2: 'PiUserSquareFill',
  Users: 'PiUsersFill',
  UsersRound: 'PiUsersThreeFill',
  Video: 'PiVideoCameraFill',
  VideoOff: 'PiVideoCameraSlashFill',
  Volume2: 'PiSpeakerHighFill',
  VolumeX: 'PiSpeakerSlashFill',
  Wallet: 'PiWalletFill',
  Wand2: 'PiMagicWandFill',
  X: 'PiXBold',
  XCircle: 'PiXCircleFill',
  Zap: 'PiLightningFill',
  ZoomIn: 'PiMagnifyingGlassPlusFill',
  ZoomOut: 'PiMagnifyingGlassMinusFill',
};

const missing = [];
for (const [lucide, pName] of Object.entries(map)) {
  if (!availableIcons.includes(pName)) {
    missing.push(pName);
  }
}
console.log('Missing icons:', missing);
